import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Providers } from '@/redux/Provider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body>

        <Providers>

          <div className="h-full">
            <Navbar />
            <div style={{ height: 'calc(100% - 56px)' }}>
              {children}
            </div>
          </div>

        </Providers>
      </body>
    </html>

  )
}
